package plugins

import (
	"fmt"
	"plugin"
	"sync"

	"github.com/Teomazivila/maz-term/pkg/models"
)

// Plugin represents a plugin for the terminal dashboard
type Plugin interface {
	// Initialize initializes the plugin with the given configuration
	Initialize(config map[string]interface{}) error

	// Name returns the name of the plugin
	Name() string

	// Version returns the version of the plugin
	Version() string

	// Description returns a brief description of the plugin
	Description() string

	// Collect collects data from the plugin source
	Collect() (interface{}, error)

	// GetMetrics returns metrics collected by the plugin
	GetMetrics() []models.Metric

	// GetNotifications returns notifications generated by the plugin
	GetNotifications() []models.Notification

	// GetConfigSchema returns the configuration schema for the plugin
	GetConfigSchema() map[string]string

	// Shutdown performs cleanup when the plugin is unloaded
	Shutdown() error
}

// PluginManager manages plugins for the terminal dashboard
type PluginManager struct {
	plugins     map[string]Plugin
	pluginPaths map[string]string
	mutex       sync.RWMutex
}

// NewPluginManager creates a new plugin manager
func NewPluginManager() *PluginManager {
	return &PluginManager{
		plugins:     make(map[string]Plugin),
		pluginPaths: make(map[string]string),
	}
}

// LoadPlugin loads a plugin from the given path
func (pm *PluginManager) LoadPlugin(path string) error {
	// Load the plugin
	plug, err := plugin.Open(path)
	if err != nil {
		return fmt.Errorf("failed to open plugin %s: %w", path, err)
	}

	// Look up the NewPlugin symbol
	symPlugin, err := plug.Lookup("NewPlugin")
	if err != nil {
		return fmt.Errorf("plugin %s does not export NewPlugin symbol: %w", path, err)
	}

	// Assert that the symbol is a function that returns a Plugin
	newPlugin, ok := symPlugin.(func() Plugin)
	if !ok {
		return fmt.Errorf("plugin %s does not export NewPlugin function with correct signature", path)
	}

	// Create a new instance of the plugin
	instance := newPlugin()

	// Get plugin name
	name := instance.Name()

	// Add to plugins map
	pm.mutex.Lock()
	pm.plugins[name] = instance
	pm.pluginPaths[name] = path
	pm.mutex.Unlock()

	return nil
}

// InitializePlugin initializes a plugin with the given configuration
func (pm *PluginManager) InitializePlugin(name string, config map[string]interface{}) error {
	pm.mutex.RLock()
	plugin, exists := pm.plugins[name]
	pm.mutex.RUnlock()

	if !exists {
		return fmt.Errorf("plugin %s not found", name)
	}

	return plugin.Initialize(config)
}

// GetPlugin returns a plugin by name
func (pm *PluginManager) GetPlugin(name string) (Plugin, error) {
	pm.mutex.RLock()
	plugin, exists := pm.plugins[name]
	pm.mutex.RUnlock()

	if !exists {
		return nil, fmt.Errorf("plugin %s not found", name)
	}

	return plugin, nil
}

// GetPlugins returns all loaded plugins
func (pm *PluginManager) GetPlugins() []Plugin {
	pm.mutex.RLock()
	defer pm.mutex.RUnlock()

	plugins := make([]Plugin, 0, len(pm.plugins))
	for _, plugin := range pm.plugins {
		plugins = append(plugins, plugin)
	}

	return plugins
}

// UnloadPlugin unloads a plugin by name
func (pm *PluginManager) UnloadPlugin(name string) error {
	pm.mutex.Lock()
	defer pm.mutex.Unlock()

	plugin, exists := pm.plugins[name]
	if !exists {
		return fmt.Errorf("plugin %s not found", name)
	}

	// Shutdown the plugin
	if err := plugin.Shutdown(); err != nil {
		return fmt.Errorf("failed to shutdown plugin %s: %w", name, err)
	}

	// Remove from maps
	delete(pm.plugins, name)
	delete(pm.pluginPaths, name)

	return nil
}

// CollectPluginData collects data from all plugins
func (pm *PluginManager) CollectPluginData() map[string]interface{} {
	pm.mutex.RLock()
	defer pm.mutex.RUnlock()

	data := make(map[string]interface{})
	for name, plugin := range pm.plugins {
		if result, err := plugin.Collect(); err == nil {
			data[name] = result
		}
	}

	return data
}

// GetAllMetrics returns metrics from all plugins
func (pm *PluginManager) GetAllMetrics() []models.Metric {
	pm.mutex.RLock()
	defer pm.mutex.RUnlock()

	var allMetrics []models.Metric
	for _, plugin := range pm.plugins {
		metrics := plugin.GetMetrics()
		allMetrics = append(allMetrics, metrics...)
	}

	return allMetrics
}

// GetAllNotifications returns notifications from all plugins
func (pm *PluginManager) GetAllNotifications() []models.Notification {
	pm.mutex.RLock()
	defer pm.mutex.RUnlock()

	var allNotifications []models.Notification
	for _, plugin := range pm.plugins {
		notifications := plugin.GetNotifications()
		allNotifications = append(allNotifications, notifications...)
	}

	return allNotifications
}

// ShutdownAll shuts down all plugins
func (pm *PluginManager) ShutdownAll() []error {
	pm.mutex.Lock()
	defer pm.mutex.Unlock()

	var errors []error
	for name, plugin := range pm.plugins {
		if err := plugin.Shutdown(); err != nil {
			errors = append(errors, fmt.Errorf("failed to shutdown plugin %s: %w", name, err))
		}
	}

	// Clear maps
	pm.plugins = make(map[string]Plugin)
	pm.pluginPaths = make(map[string]string)

	return errors
}
