package main

import (
	"fmt"
	"math"
	"math/rand"
	"time"

	"github.com/Teomazivila/maz-term/pkg/models"
	"github.com/Teomazivila/maz-term/pkg/plugins"
)

// SamplePlugin is a simple example plugin
type SamplePlugin struct {
	name          string
	version       string
	description   string
	configured    bool
	interval      time.Duration
	metrics       []models.Metric
	notifications []models.Notification
	lastCollect   time.Time
}

// NewPlugin is the exported plugin constructor
func NewPlugin() plugins.Plugin {
	return &SamplePlugin{
		name:          "sample",
		version:       "1.0.0",
		description:   "A sample plugin for demonstration purposes",
		interval:      30 * time.Second,
		metrics:       []models.Metric{},
		notifications: []models.Notification{},
		lastCollect:   time.Now(),
	}
}

// Initialize initializes the plugin with the given configuration
func (p *SamplePlugin) Initialize(config map[string]interface{}) error {
	// Get interval from config, with fallback to default
	if intervalStr, ok := config["interval"].(string); ok {
		if interval, err := time.ParseDuration(intervalStr); err == nil {
			p.interval = interval
		}
	}

	p.configured = true
	return nil
}

// Name returns the name of the plugin
func (p *SamplePlugin) Name() string {
	return p.name
}

// Version returns the version of the plugin
func (p *SamplePlugin) Version() string {
	return p.version
}

// Description returns a brief description of the plugin
func (p *SamplePlugin) Description() string {
	return p.description
}

// Collect collects data from the plugin source
func (p *SamplePlugin) Collect() (interface{}, error) {
	// Skip collection if we're within the interval
	if time.Since(p.lastCollect) < p.interval {
		return p.metrics, nil
	}

	p.lastCollect = time.Now()

	// Generate random metrics
	p.metrics = []models.Metric{
		{
			Name:      "sample.random",
			Value:     rand.Float64() * 100,
			Unit:      "%",
			Timestamp: time.Now(),
			Source:    "sample",
			Tags: map[string]string{
				"type": "random",
			},
		},
		{
			Name:      "sample.sine",
			Value:     (1 + math.Sin(float64(time.Now().UnixNano())/1e9)) * 50,
			Unit:      "units",
			Timestamp: time.Now(),
			Source:    "sample",
			Tags: map[string]string{
				"type": "sine",
			},
		},
	}

	// Generate a sample notification occasionally
	if rand.Intn(10) == 0 {
		// Create a notification
		notification := models.Notification{
			ID:        fmt.Sprintf("sample_%d", time.Now().UnixNano()),
			Title:     "Sample Notification",
			Message:   "This is a sample notification from the sample plugin.",
			Timestamp: time.Now(),
			Severity:  models.NotificationInfo,
			Source:    models.SourceSystem,
			Read:      false,
			Dismissed: false,
		}

		// Add the notification
		p.notifications = append(p.notifications, notification)
	}

	return map[string]interface{}{
		"metrics":       p.metrics,
		"notifications": p.notifications,
	}, nil
}

// GetMetrics returns metrics collected by the plugin
func (p *SamplePlugin) GetMetrics() []models.Metric {
	return p.metrics
}

// GetNotifications returns notifications generated by the plugin
func (p *SamplePlugin) GetNotifications() []models.Notification {
	return p.notifications
}

// GetConfigSchema returns the configuration schema for the plugin
func (p *SamplePlugin) GetConfigSchema() map[string]string {
	return map[string]string{
		"interval": "Duration between data collections (e.g., 30s, 1m)",
	}
}

// Shutdown performs cleanup when the plugin is unloaded
func (p *SamplePlugin) Shutdown() error {
	p.configured = false
	return nil
}

// Methods for internal use
func (p *SamplePlugin) String() string {
	return fmt.Sprintf("%s v%s - %s", p.name, p.version, p.description)
}
